### ISSUE TITLE
binutils are killing me

### ISSUE THREAD

**Issue by shufan123** [eudemonics/scaredycat#3]
what should i do if i have an x64 architecture
I am on ubuntu 12.0.2

---

your local binutils won't be used because architecture 'i686' is not supported.
[!] Could not find 'as' installed for ContextType(arch = 'arm', bits = 32, endian = 'little')
    Try installing binutils for this architecture:
        https://pwntools.readthedocs.org/en/latest/install/binutils.html
Traceback (most recent call last):
  File "scaredycat.py", line 498, in <module>
    main()
  File "scaredycat.py", line 491, in main
    find_rop_gadgets(libcfile)
  File "scaredycat.py", line 175, in find_rop_gadgets
    stack_pivot = find_arm_gadget(e, pivot_asm)
  File "scaredycat.py", line 112, in find_arm_gadget
    gadget_bytes = asm.asm(gadget, arch='arm')
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/asm.py", line 335, in asm
    assembler = _assembler()
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/asm.py", line 120, in _assembler
    gas = which_binutils('as')
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/asm.py", line 117, in which_binutils
    raise Exception('Could not find %(util)r installed for %(context)s' % locals())

```
Exception: Could not find 'as' installed for ContextType(arch = 'arm', bits = 32, endian = 'little')
```

---

this is the error .....thanks 

P.S.
I have tried the bash file

**Comment by eudemonics** [comment]
do you have the android ndk or the android arm toolchain installed on your system and in your path? if you are setting arch='arm,' it is looking for a binary called something like 'arm-linux-androideabi-as' in your system and the error is that it can't find it.. if it is 64 bit arm you would change to  arch='aarch64' and then it would be looking for 'aarch64-linux-android-as'

**Comment by shufan123** [comment]
@eudemonics i installed the gcc-4.6-arm-linux-geabi(should i have installed the android ones?cause it seems the batch accepted it) and i had `psutils missing` error so i installed the python-psutils and now i have a different error .... going to file a new issue

**Comment by sgang007** [comment]
@shufan123 Install the binutils directly from apt. Enter `apt-cache search binutils | grep arm` to check which version of binutils on arm are supported for your linux distro. If you get any output from the above command, install them by `sudo apt-get install binutils-arm*` else, you have to compile binutils from source using the shell script given in the link mentioned in the error
